-- Durable idempotency: DB-backed deduplication for webhook events
-- The application checks existing payment_id/order_id/invoice_id before inserting.
-- Redis remains the fast-path cache; DB check is the durable fallback.
-- No schema changes required — uses existing columns + application-level checks.
--
-- Optional: add unique partial indexes if you want DB-level enforcement too.
-- These are safe to add since simulator events use TEST_ prefixes (excluded).
--
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_recovery_events_payment_id_unique
--   ON recovery_events (payment_id)
--   WHERE payment_id IS NOT NULL AND payment_id NOT LIKE 'pay_TEST_%';
--
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_recovery_events_order_id_unique
--   ON recovery_events (order_id)
--   WHERE order_id IS NOT NULL AND order_id NOT LIKE 'order_TEST_%';
--
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_recovery_events_invoice_id_unique
--   ON recovery_events (invoice_id)
--   WHERE invoice_id IS NOT NULL;
